import { GenerationOptions, GenerationResult } from './gemini';
import { generateDemoImage } from '../data/demoData';
import { GoogleGenAI } from '@google/genai';

export const generateStreetFashion = async (options: GenerationOptions): Promise<GenerationResult> => {
  // 1. Try backend endpoint first
  try {
    const response = await fetch('/api/generate-street', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(options)
    });

    if (response.ok) {
      const data = await response.json();
      if (data.image) {
        return {
          image: data.image,
          headline: data.headline || 'NØRAI STREET EDITORIAL',
          copy: data.copy || 'Urban fashion synthesis generated by NØRAI AI engine.',
          engine: data.engine || options.engine,
          isDemo: Boolean(data.isDemo)
        };
      }
    }
  } catch (err: any) {
    console.warn('[NØRAI API] Backend server unreachable, checking client-side API key fallback...');
  }

  // 2. Client-side direct API generation if user provided an API Key in ApiKeyDialog
  if (options.apiKey) {
    try {
      if (options.engine === 'gemini') {
        console.log('[NØRAI Client] Generating directly via Google Gemini API...');
        return await generateWithGeminiClient(options);
      } else if (options.engine === 'openai') {
        console.log('[NØRAI Client] Generating directly via OpenAI Images API...');
        return await generateWithOpenAIClient(options);
      }
    } catch (clientErr: any) {
      console.error('[NØRAI Client AI Error]:', clientErr);
      throw new Error(`Error al generar con ${options.engine.toUpperCase()}: ${clientErr.message}`);
    }
  }

  // 3. Fallback Demo Mode if no API key configured
  console.log('[NØRAI Client] Serving Fallback Demo Generation...');
  await new Promise((r) => setTimeout(r, 2000)); // Simulate delay

  const demoImg = generateDemoImage(options.scenePrompt || 'Street Fashion Editorial');
  
  return {
    image: demoImg,
    headline: options.scenePrompt ? options.scenePrompt.toUpperCase().substring(0, 25) : 'URBAN STREET EDITION',
    copy: `Synthesized high-fashion street editorial scene. Backdrop: "${options.scenePrompt || 'Street Fashion Urban scene'}". Pure silhouette integration and realistic lighting. #NØRAI #STREET #noraimoda #aiworking`,
    engine: 'demo',
    isDemo: true
  };
};

// Client-side Gemini Generation
const generateWithGeminiClient = async (options: GenerationOptions): Promise<GenerationResult> => {
  const ai = new GoogleGenAI({ apiKey: options.apiKey! });
  const parts: any[] = [];

  if (options.productImageBase64) {
    const match = options.productImageBase64.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    if (match) parts.push({ inlineData: { data: match[2], mimeType: match[1] } });
  }

  if (options.modelImageBase64) {
    const match = options.modelImageBase64.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    if (match) parts.push({ inlineData: { data: match[2], mimeType: match[1] } });
  }

  const promptText = `High-end realistic street fashion editorial photography for NØRAI STREET.
Scene & Aesthetic: ${options.scenePrompt || 'Urban raw street fashion backdrop with dramatic atmospheric studio lighting'}.
Model Pose & Styling: High-fashion, modern proportions, crisp urban texture, realistic skin and fabric weight.
Branding: Include subtle background typography with the word "NØRAI STREET" integrated into the urban backdrop.`;

  parts.push({ text: promptText });

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: { parts },
    config: {
      imageConfig: { aspectRatio: '3:4', imageSize: '1K' }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return {
        image: `data:image/png;base64,${part.inlineData.data}`,
        headline: options.scenePrompt ? options.scenePrompt.toUpperCase().substring(0, 24) : 'URBAN STREET EDITION',
        copy: `Synthesized street style editorial photo. Concept: "${options.scenePrompt || 'Street Fashion Edition'}". #NØRAI #STREET #noraimoda`,
        engine: 'gemini'
      };
    }
  }
  throw new Error('No image returned from Gemini AI model.');
};

// Client-side OpenAI Generation
const generateWithOpenAIClient = async (options: GenerationOptions): Promise<GenerationResult> => {
  const promptText = `High-end realistic street fashion editorial photography for NØRAI STREET. Scene: ${options.scenePrompt || 'Urban raw street style'}. Include background typography NØRAI STREET.`;

  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${options.apiKey}`
    },
    body: JSON.stringify({
      model: 'dall-e-3',
      prompt: promptText,
      n: 1,
      size: '1024x1792',
      quality: 'hd',
      response_format: 'b64_json'
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `OpenAI API error status ${res.status}`);
  }

  const data = await res.json();
  if (data.data?.[0]?.b64_json) {
    return {
      image: `data:image/png;base64,${data.data[0].b64_json}`,
      headline: options.scenePrompt ? options.scenePrompt.toUpperCase().substring(0, 24) : 'OPENAI STREET EDITION',
      copy: `OpenAI DALL-E 3 high-resolution street fashion editorial. Scene: "${options.scenePrompt || 'Urban Street Style'}". #NØRAI #STREET #DALL-E3`,
      engine: 'openai'
    };
  }
  throw new Error('No image returned from OpenAI API.');
};
